# standard imports
import unittest

# third party imports

# local imports
from elementary import ReactionID
from elementary import to_endf_reaction_number

class Test_elementary_to_endf_reaction_number( unittest.TestCase ) :
    """Unit test for the to_endf_reaction_number function."""

    def test_values( self ) :

        # incident neutrons
        self.assertTrue( 2, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56' ) ) )
        self.assertTrue( 3, to_endf_reaction_number( ReactionID( 'n,Fe56->non-elastic' ) ) )
        self.assertTrue( 5, to_endf_reaction_number( ReactionID( 'n,Fe56->anything' ) ) )
        self.assertTrue( 101, to_endf_reaction_number( ReactionID( 'n,Fe56->disappearance' ) ) )
        self.assertTrue( 27,  to_endf_reaction_number( ReactionID( 'n,Fe56->absorption' ) ) )

        self.assertTrue( 11, to_endf_reaction_number( ReactionID( 'n,Fe56->n,n,h2,Mn53' ) ) )
        self.assertTrue( 875, to_endf_reaction_number( ReactionID( 'n,Fe56->n,n,Fe55' ) ) )   # not 16
        self.assertTrue( 17, to_endf_reaction_number( ReactionID( 'n,Fe56->n,n,n,Fe54' ) ) )
        self.assertTrue( 22, to_endf_reaction_number( ReactionID( 'n,Fe56->n,he4,Cr52' ) ) )
        self.assertTrue( 23, to_endf_reaction_number( ReactionID( 'n,Fe56->n,he4,he4,he4,Ca44' ) ) )
        self.assertTrue( 24, to_endf_reaction_number( ReactionID( 'n,Fe56->n,n,he4,Cr51' ) ) )

        self.assertTrue( 37, to_endf_reaction_number( ReactionID( 'n,Fe56->n,n,n,n,Fe53' ) ) )

        self.assertTrue( 51, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e1' ) ) )
        self.assertTrue( 52, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e2' ) ) )
        self.assertTrue( 53, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e3' ) ) )
        self.assertTrue( 54, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e4' ) ) )
        self.assertTrue( 55, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e5' ) ) )
        self.assertTrue( 56, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e6' ) ) )
        self.assertTrue( 57, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e7' ) ) )
        self.assertTrue( 58, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e8' ) ) )
        self.assertTrue( 59, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e9' ) ) )
        self.assertTrue( 60, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e10' ) ) )
        self.assertTrue( 61, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e11' ) ) )
        self.assertTrue( 62, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e12' ) ) )
        self.assertTrue( 63, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e13' ) ) )
        self.assertTrue( 64, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e14' ) ) )
        self.assertTrue( 65, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e15' ) ) )
        self.assertTrue( 66, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e16' ) ) )
        self.assertTrue( 67, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e17' ) ) )
        self.assertTrue( 68, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e18' ) ) )
        self.assertTrue( 69, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e19' ) ) )
        self.assertTrue( 70, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e20' ) ) )
        self.assertTrue( 71, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e21' ) ) )
        self.assertTrue( 72, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e22' ) ) )
        self.assertTrue( 73, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e23' ) ) )
        self.assertTrue( 74, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e24' ) ) )
        self.assertTrue( 75, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e25' ) ) )
        self.assertTrue( 76, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e26' ) ) )
        self.assertTrue( 77, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e27' ) ) )
        self.assertTrue( 78, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e28' ) ) )
        self.assertTrue( 79, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e29' ) ) )
        self.assertTrue( 80, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e30' ) ) )
        self.assertTrue( 81, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e31' ) ) )
        self.assertTrue( 82, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e32' ) ) )
        self.assertTrue( 83, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e33' ) ) )
        self.assertTrue( 84, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e34' ) ) )
        self.assertTrue( 85, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e35' ) ) )
        self.assertTrue( 86, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e36' ) ) )
        self.assertTrue( 87, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e37' ) ) )
        self.assertTrue( 88, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e38' ) ) )
        self.assertTrue( 89, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e39' ) ) )
        self.assertTrue( 90, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56_e40' ) ) )
        self.assertTrue( 91, to_endf_reaction_number( ReactionID( 'n,Fe56->n,Fe56[continuum]' ) ) )

        self.assertTrue( 600, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56' ) ) )
        self.assertTrue( 601, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e1' ) ) )
        self.assertTrue( 602, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e2' ) ) )
        self.assertTrue( 603, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e3' ) ) )
        self.assertTrue( 604, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e4' ) ) )
        self.assertTrue( 605, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e5' ) ) )
        self.assertTrue( 606, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e6' ) ) )
        self.assertTrue( 607, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e7' ) ) )
        self.assertTrue( 608, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e8' ) ) )
        self.assertTrue( 609, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e9' ) ) )
        self.assertTrue( 610, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e10' ) ));
        self.assertTrue( 611, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e11' ) ));
        self.assertTrue( 612, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e12' ) ));
        self.assertTrue( 613, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e13' ) ));
        self.assertTrue( 614, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e14' ) ));
        self.assertTrue( 615, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e15' ) ));
        self.assertTrue( 616, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e16' ) ));
        self.assertTrue( 617, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e17' ) ));
        self.assertTrue( 618, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e18' ) ));
        self.assertTrue( 619, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e19' ) ));
        self.assertTrue( 620, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e20' ) ));
        self.assertTrue( 621, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e21' ) ));
        self.assertTrue( 622, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e22' ) ));
        self.assertTrue( 623, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e23' ) ));
        self.assertTrue( 624, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e24' ) ));
        self.assertTrue( 625, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e25' ) ));
        self.assertTrue( 626, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e26' ) ));
        self.assertTrue( 627, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e27' ) ));
        self.assertTrue( 628, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e28' ) ));
        self.assertTrue( 629, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e29' ) ));
        self.assertTrue( 630, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e30' ) ));
        self.assertTrue( 631, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e31' ) ));
        self.assertTrue( 632, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e32' ) ));
        self.assertTrue( 633, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e33' ) ));
        self.assertTrue( 634, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e34' ) ));
        self.assertTrue( 635, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e35' ) ));
        self.assertTrue( 636, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e36' ) ));
        self.assertTrue( 637, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e37' ) ));
        self.assertTrue( 638, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e38' ) ));
        self.assertTrue( 639, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e39' ) ));
        self.assertTrue( 640, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e40' ) ));
        self.assertTrue( 641, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e41' ) ));
        self.assertTrue( 642, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e42' ) ));
        self.assertTrue( 643, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e43' ) ));
        self.assertTrue( 644, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e44' ) ));
        self.assertTrue( 645, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e45' ) ));
        self.assertTrue( 646, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e46' ) ));
        self.assertTrue( 647, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e47' ) ));
        self.assertTrue( 648, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56_e48' ) ));
        self.assertTrue( 649, to_endf_reaction_number( ReactionID( 'n,Fe56->p,Mn56[continuum]' ) ) )
        self.assertTrue( 650, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55' ) ) )
        self.assertTrue( 651, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e1' ) ) )
        self.assertTrue( 652, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e2' ) ) )
        self.assertTrue( 653, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e3' ) ) )
        self.assertTrue( 654, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e4' ) ) )
        self.assertTrue( 655, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e5' ) ) )
        self.assertTrue( 656, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e6' ) ) )
        self.assertTrue( 657, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e7' ) ) )
        self.assertTrue( 658, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e8' ) ) )
        self.assertTrue( 659, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e9' ) ) )
        self.assertTrue( 660, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e10' ) ) )
        self.assertTrue( 661, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e11' ) ) )
        self.assertTrue( 662, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e12' ) ) )
        self.assertTrue( 663, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e13' ) ) )
        self.assertTrue( 664, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e14' ) ) )
        self.assertTrue( 665, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e15' ) ) )
        self.assertTrue( 666, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e16' ) ) )
        self.assertTrue( 667, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e17' ) ) )
        self.assertTrue( 668, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e18' ) ) )
        self.assertTrue( 669, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e19' ) ) )
        self.assertTrue( 670, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e20' ) ) )
        self.assertTrue( 671, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e21' ) ) )
        self.assertTrue( 672, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e22' ) ) )
        self.assertTrue( 673, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e23' ) ) )
        self.assertTrue( 674, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e24' ) ) )
        self.assertTrue( 675, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e25' ) ) )
        self.assertTrue( 676, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e26' ) ) )
        self.assertTrue( 677, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e27' ) ) )
        self.assertTrue( 678, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e28' ) ) )
        self.assertTrue( 679, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e29' ) ) )
        self.assertTrue( 680, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e30' ) ) )
        self.assertTrue( 681, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e31' ) ) )
        self.assertTrue( 682, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e32' ) ) )
        self.assertTrue( 683, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e33' ) ) )
        self.assertTrue( 684, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e34' ) ) )
        self.assertTrue( 685, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e35' ) ) )
        self.assertTrue( 686, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e36' ) ) )
        self.assertTrue( 687, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e37' ) ) )
        self.assertTrue( 688, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e38' ) ) )
        self.assertTrue( 689, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e39' ) ) )
        self.assertTrue( 690, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e40' ) ) )
        self.assertTrue( 691, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e41' ) ) )
        self.assertTrue( 692, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e42' ) ) )
        self.assertTrue( 693, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e43' ) ) )
        self.assertTrue( 694, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e44' ) ) )
        self.assertTrue( 695, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e45' ) ) )
        self.assertTrue( 696, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e46' ) ) )
        self.assertTrue( 697, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e47' ) ) )
        self.assertTrue( 698, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55_e48' ) ) )
        self.assertTrue( 699, to_endf_reaction_number( ReactionID( 'n,Fe56->h2,Mn55[continuum]' ) ) )
        self.assertTrue( 700, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54' ) ) )
        self.assertTrue( 701, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e1' ) ) )
        self.assertTrue( 702, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e2' ) ) )
        self.assertTrue( 703, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e3' ) ) )
        self.assertTrue( 704, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e4' ) ) )
        self.assertTrue( 705, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e5' ) ) )
        self.assertTrue( 706, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e6' ) ) )
        self.assertTrue( 707, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e7' ) ) )
        self.assertTrue( 708, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e8' ) ) )
        self.assertTrue( 709, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e9' ) ) )
        self.assertTrue( 710, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e10' ) ) )
        self.assertTrue( 711, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e11' ) ) )
        self.assertTrue( 712, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e12' ) ) )
        self.assertTrue( 713, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e13' ) ) )
        self.assertTrue( 714, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e14' ) ) )
        self.assertTrue( 715, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e15' ) ) )
        self.assertTrue( 716, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e16' ) ) )
        self.assertTrue( 717, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e17' ) ) )
        self.assertTrue( 718, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e18' ) ) )
        self.assertTrue( 719, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e19' ) ) )
        self.assertTrue( 720, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e20' ) ) )
        self.assertTrue( 721, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e21' ) ) )
        self.assertTrue( 722, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e22' ) ) )
        self.assertTrue( 723, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e23' ) ) )
        self.assertTrue( 724, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e24' ) ) )
        self.assertTrue( 725, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e25' ) ) )
        self.assertTrue( 726, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e26' ) ) )
        self.assertTrue( 727, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e27' ) ) )
        self.assertTrue( 728, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e28' ) ) )
        self.assertTrue( 729, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e29' ) ) )
        self.assertTrue( 730, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e30' ) ) )
        self.assertTrue( 731, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e31' ) ) )
        self.assertTrue( 732, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e32' ) ) )
        self.assertTrue( 733, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e33' ) ) )
        self.assertTrue( 734, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e34' ) ) )
        self.assertTrue( 735, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e35' ) ) )
        self.assertTrue( 736, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e36' ) ) )
        self.assertTrue( 737, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e37' ) ) )
        self.assertTrue( 738, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e38' ) ) )
        self.assertTrue( 739, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e39' ) ) )
        self.assertTrue( 740, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e40' ) ) )
        self.assertTrue( 741, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e41' ) ) )
        self.assertTrue( 742, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e42' ) ) )
        self.assertTrue( 743, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e43' ) ) )
        self.assertTrue( 744, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e44' ) ) )
        self.assertTrue( 745, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e45' ) ) )
        self.assertTrue( 746, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e46' ) ) )
        self.assertTrue( 747, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e47' ) ) )
        self.assertTrue( 748, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54_e48' ) ) )
        self.assertTrue( 749, to_endf_reaction_number( ReactionID( 'n,Fe56->h3,Mn54[continuum]' ) ) )
        self.assertTrue( 750, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54' ) ) )
        self.assertTrue( 751, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e1' ) ) )
        self.assertTrue( 752, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e2' ) ) )
        self.assertTrue( 753, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e3' ) ) )
        self.assertTrue( 754, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e4' ) ) )
        self.assertTrue( 755, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e5' ) ) )
        self.assertTrue( 756, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e6' ) ) )
        self.assertTrue( 757, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e7' ) ) )
        self.assertTrue( 758, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e8' ) ) )
        self.assertTrue( 759, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e9' ) ) )
        self.assertTrue( 760, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e10' ) ) )
        self.assertTrue( 761, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e11' ) ) )
        self.assertTrue( 762, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e12' ) ) )
        self.assertTrue( 763, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e13' ) ) )
        self.assertTrue( 764, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e14' ) ) )
        self.assertTrue( 765, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e15' ) ) )
        self.assertTrue( 766, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e16' ) ) )
        self.assertTrue( 767, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e17' ) ) )
        self.assertTrue( 768, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e18' ) ) )
        self.assertTrue( 769, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e19' ) ) )
        self.assertTrue( 770, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e20' ) ) )
        self.assertTrue( 771, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e21' ) ) )
        self.assertTrue( 772, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e22' ) ) )
        self.assertTrue( 773, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e23' ) ) )
        self.assertTrue( 774, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e24' ) ) )
        self.assertTrue( 775, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e25' ) ) )
        self.assertTrue( 776, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e26' ) ) )
        self.assertTrue( 777, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e27' ) ) )
        self.assertTrue( 778, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e28' ) ) )
        self.assertTrue( 779, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e29' ) ) )
        self.assertTrue( 780, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e30' ) ) )
        self.assertTrue( 781, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e31' ) ) )
        self.assertTrue( 782, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e32' ) ) )
        self.assertTrue( 783, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e33' ) ) )
        self.assertTrue( 784, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e34' ) ) )
        self.assertTrue( 785, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e35' ) ) )
        self.assertTrue( 786, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e36' ) ) )
        self.assertTrue( 787, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e37' ) ) )
        self.assertTrue( 788, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e38' ) ) )
        self.assertTrue( 789, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e39' ) ) )
        self.assertTrue( 790, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e40' ) ) )
        self.assertTrue( 791, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e41' ) ) )
        self.assertTrue( 792, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e42' ) ) )
        self.assertTrue( 793, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e43' ) ) )
        self.assertTrue( 794, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e44' ) ) )
        self.assertTrue( 795, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e45' ) ) )
        self.assertTrue( 796, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e46' ) ) )
        self.assertTrue( 797, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e47' ) ) )
        self.assertTrue( 798, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54_e48' ) ) )
        self.assertTrue( 799, to_endf_reaction_number( ReactionID( 'n,Fe56->he3,Cr54[continuum]' ) ) )
        self.assertTrue( 800, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53' ) ) )
        self.assertTrue( 801, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e1' ) ) )
        self.assertTrue( 802, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e2' ) ) )
        self.assertTrue( 803, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e3' ) ) )
        self.assertTrue( 804, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e4' ) ) )
        self.assertTrue( 805, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e5' ) ) )
        self.assertTrue( 806, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e6' ) ) )
        self.assertTrue( 807, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e7' ) ) )
        self.assertTrue( 808, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e8' ) ) )
        self.assertTrue( 809, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e9' ) ) )
        self.assertTrue( 810, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e10' ) ) )
        self.assertTrue( 811, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e11' ) ) )
        self.assertTrue( 812, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e12' ) ) )
        self.assertTrue( 813, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e13' ) ) )
        self.assertTrue( 814, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e14' ) ) )
        self.assertTrue( 815, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e15' ) ) )
        self.assertTrue( 816, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e16' ) ) )
        self.assertTrue( 817, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e17' ) ) )
        self.assertTrue( 818, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e18' ) ) )
        self.assertTrue( 819, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e19' ) ) )
        self.assertTrue( 820, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e20' ) ) )
        self.assertTrue( 821, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e21' ) ) )
        self.assertTrue( 822, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e22' ) ) )
        self.assertTrue( 823, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e23' ) ) )
        self.assertTrue( 824, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e24' ) ) )
        self.assertTrue( 825, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e25' ) ) )
        self.assertTrue( 826, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e26' ) ) )
        self.assertTrue( 827, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e27' ) ) )
        self.assertTrue( 828, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e28' ) ) )
        self.assertTrue( 829, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e29' ) ) )
        self.assertTrue( 830, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e30' ) ) )
        self.assertTrue( 831, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e31' ) ) )
        self.assertTrue( 832, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e32' ) ) )
        self.assertTrue( 833, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e33' ) ) )
        self.assertTrue( 834, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e34' ) ) )
        self.assertTrue( 835, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e35' ) ) )
        self.assertTrue( 836, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e36' ) ) )
        self.assertTrue( 837, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e37' ) ) )
        self.assertTrue( 838, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e38' ) ) )
        self.assertTrue( 839, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e39' ) ) )
        self.assertTrue( 840, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e40' ) ) )
        self.assertTrue( 841, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e41' ) ) )
        self.assertTrue( 842, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e42' ) ) )
        self.assertTrue( 843, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e43' ) ) )
        self.assertTrue( 844, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e44' ) ) )
        self.assertTrue( 845, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e45' ) ) )
        self.assertTrue( 846, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e46' ) ) )
        self.assertTrue( 847, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e47' ) ) )
        self.assertTrue( 848, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53_e48' ) ) )
        self.assertTrue( 849, to_endf_reaction_number( ReactionID( 'n,Fe56->he4,Cr53[continuum]' ) ) )
        self.assertTrue( 875, to_endf_reaction_number( ReactionID( 'n,Fe56->n,n,Fe55' ) ) )
        self.assertTrue( 876, to_endf_reaction_number( ReactionID( 'n,Fe56->n,n,Fe55_e1' ) ) )
        self.assertTrue( 877, to_endf_reaction_number( ReactionID( 'n,Fe56->n,n,Fe55_e2' ) ) )
        self.assertTrue( 878, to_endf_reaction_number( ReactionID( 'n,Fe56->n,n,Fe55_e3' ) ) )
        self.assertTrue( 879, to_endf_reaction_number( ReactionID( 'n,Fe56->n,n,Fe55_e4' ) ) )
        self.assertTrue( 880, to_endf_reaction_number( ReactionID( 'n,Fe56->n,n,Fe55_e5' ) ) )
        self.assertTrue( 881, to_endf_reaction_number( ReactionID( 'n,Fe56->n,n,Fe55_e6' ) ) )
        self.assertTrue( 882, to_endf_reaction_number( ReactionID( 'n,Fe56->n,n,Fe55_e7' ) ) )
        self.assertTrue( 883, to_endf_reaction_number( ReactionID( 'n,Fe56->n,n,Fe55_e8' ) ) )
        self.assertTrue( 884, to_endf_reaction_number( ReactionID( 'n,Fe56->n,n,Fe55_e9' ) ) )
        self.assertTrue( 885, to_endf_reaction_number( ReactionID( 'n,Fe56->n,n,Fe55_e10' ) ) )
        self.assertTrue( 886, to_endf_reaction_number( ReactionID( 'n,Fe56->n,n,Fe55_e11' ) ) )
        self.assertTrue( 887, to_endf_reaction_number( ReactionID( 'n,Fe56->n,n,Fe55_e12' ) ) )
        self.assertTrue( 888, to_endf_reaction_number( ReactionID( 'n,Fe56->n,n,Fe55_e13' ) ) )
        self.assertTrue( 889, to_endf_reaction_number( ReactionID( 'n,Fe56->n,n,Fe55_e14' ) ) )
        self.assertTrue( 890, to_endf_reaction_number( ReactionID( 'n,Fe56->n,n,Fe55_e15' ) ) )
        self.assertTrue( 891, to_endf_reaction_number( ReactionID( 'n,Fe56->n,n,Fe55[continuum]' ) ) )

        # incident protons
        self.assertTrue( 2, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56' ) ) )
        self.assertTrue( 3, to_endf_reaction_number( ReactionID( 'p,Fe56->non-elastic' ) ) )
        self.assertTrue( 5, to_endf_reaction_number( ReactionID( 'p,Fe56->anything' ) ) )
        self.assertTrue( 101, to_endf_reaction_number( ReactionID( 'p,Fe56->disappearance' ) ) )
        self.assertTrue( 27,  to_endf_reaction_number( ReactionID( 'p,Fe56->absorption' ) ) )

        self.assertTrue( 11, to_endf_reaction_number( ReactionID( 'p,Fe56->n,n,h2,Fe53' ) ) )
        self.assertTrue( 875, to_endf_reaction_number( ReactionID( 'p,Fe56->n,n,Co55' ) ) )   # not 16
        self.assertTrue( 17, to_endf_reaction_number( ReactionID( 'p,Fe56->n,n,n,Co54' ) ) )
        self.assertTrue( 22, to_endf_reaction_number( ReactionID( 'p,Fe56->n,he4,Mn52' ) ) )
        self.assertTrue( 23, to_endf_reaction_number( ReactionID( 'p,Fe56->n,he4,he4,he4,Sc44' ) ) )
        self.assertTrue( 24, to_endf_reaction_number( ReactionID( 'p,Fe56->n,n,he4,Mn51' ) ) )

        self.assertTrue( 37, to_endf_reaction_number( ReactionID( 'p,Fe56->n,n,n,n,Co53' ) ) )

        self.assertTrue( 50, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56' ) ) )
        self.assertTrue( 51, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e1' ) ) )
        self.assertTrue( 52, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e2' ) ) )
        self.assertTrue( 53, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e3' ) ) )
        self.assertTrue( 54, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e4' ) ) )
        self.assertTrue( 55, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e5' ) ) )
        self.assertTrue( 56, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e6' ) ) )
        self.assertTrue( 57, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e7' ) ) )
        self.assertTrue( 58, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e8' ) ) )
        self.assertTrue( 59, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e9' ) ) )
        self.assertTrue( 60, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e10' ) ) )
        self.assertTrue( 61, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e11' ) ) )
        self.assertTrue( 62, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e12' ) ) )
        self.assertTrue( 63, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e13' ) ) )
        self.assertTrue( 64, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e14' ) ) )
        self.assertTrue( 65, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e15' ) ) )
        self.assertTrue( 66, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e16' ) ) )
        self.assertTrue( 67, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e17' ) ) )
        self.assertTrue( 68, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e18' ) ) )
        self.assertTrue( 69, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e19' ) ) )
        self.assertTrue( 70, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e20' ) ) )
        self.assertTrue( 71, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e21' ) ) )
        self.assertTrue( 72, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e22' ) ) )
        self.assertTrue( 73, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e23' ) ) )
        self.assertTrue( 74, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e24' ) ) )
        self.assertTrue( 75, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e25' ) ) )
        self.assertTrue( 76, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e26' ) ) )
        self.assertTrue( 77, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e27' ) ) )
        self.assertTrue( 78, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e28' ) ) )
        self.assertTrue( 79, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e29' ) ) )
        self.assertTrue( 80, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e30' ) ) )
        self.assertTrue( 81, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e31' ) ) )
        self.assertTrue( 82, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e32' ) ) )
        self.assertTrue( 83, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e33' ) ) )
        self.assertTrue( 84, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e34' ) ) )
        self.assertTrue( 85, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e35' ) ) )
        self.assertTrue( 86, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e36' ) ) )
        self.assertTrue( 87, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e37' ) ) )
        self.assertTrue( 88, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e38' ) ) )
        self.assertTrue( 89, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e39' ) ) )
        self.assertTrue( 90, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56_e40' ) ) )
        self.assertTrue( 91, to_endf_reaction_number( ReactionID( 'p,Fe56->n,Co56[continuum]' ) ) )

        self.assertTrue( 2  , to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56' ) ) )   # not 600
        self.assertTrue( 601, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e1' ) ) )
        self.assertTrue( 602, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e2' ) ) )
        self.assertTrue( 603, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e3' ) ) )
        self.assertTrue( 604, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e4' ) ) )
        self.assertTrue( 605, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e5' ) ) )
        self.assertTrue( 606, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e6' ) ) )
        self.assertTrue( 607, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e7' ) ) )
        self.assertTrue( 608, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e8' ) ) )
        self.assertTrue( 609, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e9' ) ) )
        self.assertTrue( 610, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e10' ) ) )
        self.assertTrue( 611, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e11' ) ) )
        self.assertTrue( 612, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e12' ) ) )
        self.assertTrue( 613, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e13' ) ) )
        self.assertTrue( 614, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e14' ) ) )
        self.assertTrue( 615, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e15' ) ) )
        self.assertTrue( 616, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e16' ) ) )
        self.assertTrue( 617, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e17' ) ) )
        self.assertTrue( 618, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e18' ) ) )
        self.assertTrue( 619, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e19' ) ) )
        self.assertTrue( 620, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e20' ) ) )
        self.assertTrue( 621, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e21' ) ) )
        self.assertTrue( 622, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e22' ) ) )
        self.assertTrue( 623, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e23' ) ) )
        self.assertTrue( 624, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e24' ) ) )
        self.assertTrue( 625, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e25' ) ) )
        self.assertTrue( 626, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e26' ) ) )
        self.assertTrue( 627, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e27' ) ) )
        self.assertTrue( 628, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e28' ) ) )
        self.assertTrue( 629, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e29' ) ) )
        self.assertTrue( 630, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e30' ) ) )
        self.assertTrue( 631, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e31' ) ) )
        self.assertTrue( 632, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e32' ) ) )
        self.assertTrue( 633, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e33' ) ) )
        self.assertTrue( 634, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e34' ) ) )
        self.assertTrue( 635, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e35' ) ) )
        self.assertTrue( 636, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e36' ) ) )
        self.assertTrue( 637, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e37' ) ) )
        self.assertTrue( 638, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e38' ) ) )
        self.assertTrue( 639, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e39' ) ) )
        self.assertTrue( 640, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e40' ) ) )
        self.assertTrue( 641, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e41' ) ) )
        self.assertTrue( 642, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e42' ) ) )
        self.assertTrue( 643, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e43' ) ) )
        self.assertTrue( 644, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e44' ) ) )
        self.assertTrue( 645, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e45' ) ) )
        self.assertTrue( 646, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e46' ) ) )
        self.assertTrue( 647, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e47' ) ) )
        self.assertTrue( 648, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56_e48' ) ) )
        self.assertTrue( 649, to_endf_reaction_number( ReactionID( 'p,Fe56->p,Fe56[continuum]' ) ) )
        self.assertTrue( 650, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55' ) ) )
        self.assertTrue( 651, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e1' ) ) )
        self.assertTrue( 652, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e2' ) ) )
        self.assertTrue( 653, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e3' ) ) )
        self.assertTrue( 654, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e4' ) ) )
        self.assertTrue( 655, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e5' ) ) )
        self.assertTrue( 656, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e6' ) ) )
        self.assertTrue( 657, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e7' ) ) )
        self.assertTrue( 658, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e8' ) ) )
        self.assertTrue( 659, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e9' ) ) )
        self.assertTrue( 660, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e10' ) ) )
        self.assertTrue( 661, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e11' ) ) )
        self.assertTrue( 662, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e12' ) ) )
        self.assertTrue( 663, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e13' ) ) )
        self.assertTrue( 664, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e14' ) ) )
        self.assertTrue( 665, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e15' ) ) )
        self.assertTrue( 666, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e16' ) ) )
        self.assertTrue( 667, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e17' ) ) )
        self.assertTrue( 668, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e18' ) ) )
        self.assertTrue( 669, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e19' ) ) )
        self.assertTrue( 670, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e20' ) ) )
        self.assertTrue( 671, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e21' ) ) )
        self.assertTrue( 672, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e22' ) ) )
        self.assertTrue( 673, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e23' ) ) )
        self.assertTrue( 674, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e24' ) ) )
        self.assertTrue( 675, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e25' ) ) )
        self.assertTrue( 676, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e26' ) ) )
        self.assertTrue( 677, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e27' ) ) )
        self.assertTrue( 678, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e28' ) ) )
        self.assertTrue( 679, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e29' ) ) )
        self.assertTrue( 680, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e30' ) ) )
        self.assertTrue( 681, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e31' ) ) )
        self.assertTrue( 682, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e32' ) ) )
        self.assertTrue( 683, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e33' ) ) )
        self.assertTrue( 684, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e34' ) ) )
        self.assertTrue( 685, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e35' ) ) )
        self.assertTrue( 686, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e36' ) ) )
        self.assertTrue( 687, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e37' ) ) )
        self.assertTrue( 688, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e38' ) ) )
        self.assertTrue( 689, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e39' ) ) )
        self.assertTrue( 690, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e40' ) ) )
        self.assertTrue( 691, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e41' ) ) )
        self.assertTrue( 692, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e42' ) ) )
        self.assertTrue( 693, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e43' ) ) )
        self.assertTrue( 694, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e44' ) ) )
        self.assertTrue( 695, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e45' ) ) )
        self.assertTrue( 696, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e46' ) ) )
        self.assertTrue( 697, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e47' ) ) )
        self.assertTrue( 698, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55_e48' ) ) )
        self.assertTrue( 699, to_endf_reaction_number( ReactionID( 'p,Fe56->h2,Fe55[continuum]' ) ) )
        self.assertTrue( 700, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54' ) ) )
        self.assertTrue( 701, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e1' ) ) )
        self.assertTrue( 702, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e2' ) ) )
        self.assertTrue( 703, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e3' ) ) )
        self.assertTrue( 704, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e4' ) ) )
        self.assertTrue( 705, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e5' ) ) )
        self.assertTrue( 706, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e6' ) ) )
        self.assertTrue( 707, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e7' ) ) )
        self.assertTrue( 708, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e8' ) ) )
        self.assertTrue( 709, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e9' ) ) )
        self.assertTrue( 710, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e10' ) ) )
        self.assertTrue( 711, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e11' ) ) )
        self.assertTrue( 712, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e12' ) ) )
        self.assertTrue( 713, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e13' ) ) )
        self.assertTrue( 714, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e14' ) ) )
        self.assertTrue( 715, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e15' ) ) )
        self.assertTrue( 716, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e16' ) ) )
        self.assertTrue( 717, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e17' ) ) )
        self.assertTrue( 718, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e18' ) ) )
        self.assertTrue( 719, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e19' ) ) )
        self.assertTrue( 720, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e20' ) ) )
        self.assertTrue( 721, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e21' ) ) )
        self.assertTrue( 722, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e22' ) ) )
        self.assertTrue( 723, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e23' ) ) )
        self.assertTrue( 724, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e24' ) ) )
        self.assertTrue( 725, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e25' ) ) )
        self.assertTrue( 726, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e26' ) ) )
        self.assertTrue( 727, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e27' ) ) )
        self.assertTrue( 728, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e28' ) ) )
        self.assertTrue( 729, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e29' ) ) )
        self.assertTrue( 730, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e30' ) ) )
        self.assertTrue( 731, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e31' ) ) )
        self.assertTrue( 732, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e32' ) ) )
        self.assertTrue( 733, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e33' ) ) )
        self.assertTrue( 734, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e34' ) ) )
        self.assertTrue( 735, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e35' ) ) )
        self.assertTrue( 736, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e36' ) ) )
        self.assertTrue( 737, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e37' ) ) )
        self.assertTrue( 738, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e38' ) ) )
        self.assertTrue( 739, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e39' ) ) )
        self.assertTrue( 740, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e40' ) ) )
        self.assertTrue( 741, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e41' ) ) )
        self.assertTrue( 742, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e42' ) ) )
        self.assertTrue( 743, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e43' ) ) )
        self.assertTrue( 744, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e44' ) ) )
        self.assertTrue( 745, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e45' ) ) )
        self.assertTrue( 746, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e46' ) ) )
        self.assertTrue( 747, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e47' ) ) )
        self.assertTrue( 748, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54_e48' ) ) )
        self.assertTrue( 749, to_endf_reaction_number( ReactionID( 'p,Fe56->h3,Fe54[continuum]' ) ) )
        self.assertTrue( 750, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54' ) ) )
        self.assertTrue( 751, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e1' ) ) )
        self.assertTrue( 752, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e2' ) ) )
        self.assertTrue( 753, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e3' ) ) )
        self.assertTrue( 754, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e4' ) ) )
        self.assertTrue( 755, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e5' ) ) )
        self.assertTrue( 756, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e6' ) ) )
        self.assertTrue( 757, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e7' ) ) )
        self.assertTrue( 758, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e8' ) ) )
        self.assertTrue( 759, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e9' ) ) )
        self.assertTrue( 760, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e10' ) ) )
        self.assertTrue( 761, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e11' ) ) )
        self.assertTrue( 762, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e12' ) ) )
        self.assertTrue( 763, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e13' ) ) )
        self.assertTrue( 764, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e14' ) ) )
        self.assertTrue( 765, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e15' ) ) )
        self.assertTrue( 766, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e16' ) ) )
        self.assertTrue( 767, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e17' ) ) )
        self.assertTrue( 768, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e18' ) ) )
        self.assertTrue( 769, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e19' ) ) )
        self.assertTrue( 770, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e20' ) ) )
        self.assertTrue( 771, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e21' ) ) )
        self.assertTrue( 772, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e22' ) ) )
        self.assertTrue( 773, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e23' ) ) )
        self.assertTrue( 774, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e24' ) ) )
        self.assertTrue( 775, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e25' ) ) )
        self.assertTrue( 776, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e26' ) ) )
        self.assertTrue( 777, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e27' ) ) )
        self.assertTrue( 778, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e28' ) ) )
        self.assertTrue( 779, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e29' ) ) )
        self.assertTrue( 780, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e30' ) ) )
        self.assertTrue( 781, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e31' ) ) )
        self.assertTrue( 782, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e32' ) ) )
        self.assertTrue( 783, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e33' ) ) )
        self.assertTrue( 784, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e34' ) ) )
        self.assertTrue( 785, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e35' ) ) )
        self.assertTrue( 786, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e36' ) ) )
        self.assertTrue( 787, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e37' ) ) )
        self.assertTrue( 788, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e38' ) ) )
        self.assertTrue( 789, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e39' ) ) )
        self.assertTrue( 790, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e40' ) ) )
        self.assertTrue( 791, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e41' ) ) )
        self.assertTrue( 792, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e42' ) ) )
        self.assertTrue( 793, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e43' ) ) )
        self.assertTrue( 794, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e44' ) ) )
        self.assertTrue( 795, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e45' ) ) )
        self.assertTrue( 796, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e46' ) ) )
        self.assertTrue( 797, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e47' ) ) )
        self.assertTrue( 798, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54_e48' ) ) )
        self.assertTrue( 799, to_endf_reaction_number( ReactionID( 'p,Fe56->he3,Mn54[continuum]' ) ) )
        self.assertTrue( 800, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53' ) ) )
        self.assertTrue( 801, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e1' ) ) )
        self.assertTrue( 802, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e2' ) ) )
        self.assertTrue( 803, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e3' ) ) )
        self.assertTrue( 804, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e4' ) ) )
        self.assertTrue( 805, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e5' ) ) )
        self.assertTrue( 806, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e6' ) ) )
        self.assertTrue( 807, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e7' ) ) )
        self.assertTrue( 808, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e8' ) ) )
        self.assertTrue( 809, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e9' ) ) )
        self.assertTrue( 810, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e10' ) ) )
        self.assertTrue( 811, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e11' ) ) )
        self.assertTrue( 812, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e12' ) ) )
        self.assertTrue( 813, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e13' ) ) )
        self.assertTrue( 814, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e14' ) ) )
        self.assertTrue( 815, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e15' ) ) )
        self.assertTrue( 816, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e16' ) ) )
        self.assertTrue( 817, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e17' ) ) )
        self.assertTrue( 818, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e18' ) ) )
        self.assertTrue( 819, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e19' ) ) )
        self.assertTrue( 820, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e20' ) ) )
        self.assertTrue( 821, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e21' ) ) )
        self.assertTrue( 822, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e22' ) ) )
        self.assertTrue( 823, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e23' ) ) )
        self.assertTrue( 824, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e24' ) ) )
        self.assertTrue( 825, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e25' ) ) )
        self.assertTrue( 826, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e26' ) ) )
        self.assertTrue( 827, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e27' ) ) )
        self.assertTrue( 828, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e28' ) ) )
        self.assertTrue( 829, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e29' ) ) )
        self.assertTrue( 830, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e30' ) ) )
        self.assertTrue( 831, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e31' ) ) )
        self.assertTrue( 832, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e32' ) ) )
        self.assertTrue( 833, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e33' ) ) )
        self.assertTrue( 834, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e34' ) ) )
        self.assertTrue( 835, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e35' ) ) )
        self.assertTrue( 836, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e36' ) ) )
        self.assertTrue( 837, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e37' ) ) )
        self.assertTrue( 838, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e38' ) ) )
        self.assertTrue( 839, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e39' ) ) )
        self.assertTrue( 840, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e40' ) ) )
        self.assertTrue( 841, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e41' ) ) )
        self.assertTrue( 842, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e42' ) ) )
        self.assertTrue( 843, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e43' ) ) )
        self.assertTrue( 844, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e44' ) ) )
        self.assertTrue( 845, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e45' ) ) )
        self.assertTrue( 846, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e46' ) ) )
        self.assertTrue( 847, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e47' ) ) )
        self.assertTrue( 848, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53_e48' ) ) )
        self.assertTrue( 849, to_endf_reaction_number( ReactionID( 'p,Fe56->he4,Mn53[continuum]' ) ) )
        self.assertTrue( 875, to_endf_reaction_number( ReactionID( 'p,Fe56->n,n,Co55' ) ) )
        self.assertTrue( 876, to_endf_reaction_number( ReactionID( 'p,Fe56->n,n,Co55_e1' ) ) )
        self.assertTrue( 877, to_endf_reaction_number( ReactionID( 'p,Fe56->n,n,Co55_e2' ) ) )
        self.assertTrue( 878, to_endf_reaction_number( ReactionID( 'p,Fe56->n,n,Co55_e3' ) ) )
        self.assertTrue( 879, to_endf_reaction_number( ReactionID( 'p,Fe56->n,n,Co55_e4' ) ) )
        self.assertTrue( 880, to_endf_reaction_number( ReactionID( 'p,Fe56->n,n,Co55_e5' ) ) )
        self.assertTrue( 881, to_endf_reaction_number( ReactionID( 'p,Fe56->n,n,Co55_e6' ) ) )
        self.assertTrue( 882, to_endf_reaction_number( ReactionID( 'p,Fe56->n,n,Co55_e7' ) ) )
        self.assertTrue( 883, to_endf_reaction_number( ReactionID( 'p,Fe56->n,n,Co55_e8' ) ) )
        self.assertTrue( 884, to_endf_reaction_number( ReactionID( 'p,Fe56->n,n,Co55_e9' ) ) )
        self.assertTrue( 885, to_endf_reaction_number( ReactionID( 'p,Fe56->n,n,Co55_e10' ) ) )
        self.assertTrue( 886, to_endf_reaction_number( ReactionID( 'p,Fe56->n,n,Co55_e11' ) ) )
        self.assertTrue( 887, to_endf_reaction_number( ReactionID( 'p,Fe56->n,n,Co55_e12' ) ) )
        self.assertTrue( 888, to_endf_reaction_number( ReactionID( 'p,Fe56->n,n,Co55_e13' ) ) )
        self.assertTrue( 889, to_endf_reaction_number( ReactionID( 'p,Fe56->n,n,Co55_e14' ) ) )
        self.assertTrue( 890, to_endf_reaction_number( ReactionID( 'p,Fe56->n,n,Co55_e15' ) ) )
        self.assertTrue( 891, to_endf_reaction_number( ReactionID( 'p,Fe56->n,n,Co55[continuum]' ) ) )

        # special cases
        self.assertTrue( 2, to_endf_reaction_number( ReactionID( 'n,Fe56_e1->n,Fe56' ) ) )
        self.assertTrue( 51, to_endf_reaction_number( ReactionID( 'n,Fe56_e1->n,Fe56_e1' ) ) )

if __name__ == '__main__' :

    unittest.main()
